# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- windows

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactName: 'Simple3D'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- template: templates/assetsControl.yml
  parameters:
    fileExtention: 'wav'
    count: '2'

- template: templates/assetsControl.yml
  parameters:
    fileExtention: 'dds'
    count: '5'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/Artifacts'
    artifact: '$(artifactName)'
    publishLocation: 'pipeline'

# - script: ansible-galaxy collection install community.general

# - task: Create an ISO file
#   community.general.iso_create:
#     src_files:
#       - $(Pipeline.Workspace)/Artifacts
#     dest_iso: $(Pipeline.Workspace)/ISO/test.iso
#     interchange_level: 3
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ImageBuilder'
    subscriptionId: '3a36346f-08ec-4d4a-9f19-60bd98c217c4'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(ResourceGroup)'
    location: '$(Location)'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'

